"""init schema

Revision ID: 05df3ee7cb97
Revises: 
Create Date: 2025-09-15 07:58:05.409176
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '05df3ee7cb97'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_store',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('doc_type', sa.Enum('statute', 'case_law', 'regulation', 'other', name='doctypeenum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'unknown', name='genderenum'), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_email'), 'person', ['email'], unique=True)
    op.create_table('address',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('line1', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=24), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    op.create_table('chat_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('session_type', sa.Enum('consultation', 'follow_up', 'general', name='sessiontypeenum'), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', 'closed', name='sessionstatusenum'), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_session_person_id'), 'chat_session', ['person_id'], unique=False)
    op.create_index('ix_chat_session_person_status', 'chat_session', ['person_id', 'status'], unique=False)
    op.create_table('chat_message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'bot', 'system', name='messageroleenum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('reasoning_context', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_message_session_id'), 'chat_message', ['session_id'], unique=False)
    op.create_table('chat_attachment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document_store.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_message.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'document_id', name='uq_msg_doc_once')
    )
    op.create_index(op.f('ix_chat_attachment_document_id'), 'chat_attachment', ['document_id'], unique=False)
    op.create_index(op.f('ix_chat_attachment_message_id'), 'chat_attachment', ['message_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_attachment_message_id'), table_name='chat_attachment')
    op.drop_index(op.f('ix_chat_attachment_document_id'), table_name='chat_attachment')
    op.drop_table('chat_attachment')
    op.drop_index(op.f('ix_chat_message_session_id'), table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index('ix_chat_session_person_status', table_name='chat_session')
    op.drop_index(op.f('ix_chat_session_person_id'), table_name='chat_session')
    op.drop_table('chat_session')
    op.drop_table('address')
    op.drop_index(op.f('ix_person_email'), table_name='person')
    op.drop_table('person')
    op.drop_table('document_store')
    # ### end Alembic commands ###
