"""add password reset token

Revision ID: 1ce6e9578798
Revises: 1c1a2a71b7ea
Create Date: 2026-01-01 15:11:43.092628
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '1ce6e9578798'
down_revision = '1c1a2a71b7ea'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_token_expires_at'), 'password_reset_token', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_reset_token_person_id'), 'password_reset_token', ['person_id'], unique=False)
    op.create_index(op.f('ix_password_reset_token_token_hash'), 'password_reset_token', ['token_hash'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_token_token_hash'), table_name='password_reset_token')
    op.drop_index(op.f('ix_password_reset_token_person_id'), table_name='password_reset_token')
    op.drop_index(op.f('ix_password_reset_token_expires_at'), table_name='password_reset_token')
    op.drop_table('password_reset_token')
    # ### end Alembic commands ###
