"""changes to tables

Revision ID: 33b24865e8f5
Revises: 05df3ee7cb97
Create Date: 2025-09-15 09:28:14.738598
"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33b24865e8f5'
down_revision = '05df3ee7cb97'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_session', 'topic')
    op.drop_column('chat_session', 'session_type')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_session', sa.Column('session_type', postgresql.ENUM('consultation', 'follow_up', 'general', name='sessiontypeenum'), autoincrement=False, nullable=False))
    op.add_column('chat_session', sa.Column('topic', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
